### ISSUE TITLE
Gibbs excess models????

### ISSUE THREAD

**Issue by SalvadorBrandolin** [ipqa-research/yaeos#17]
Hi

Do you plan to add some Gibbs excess models?

For example, UNIFAC and then build cubic models with Huron-Vidal mixing rules.

I see PSRK, i happy 🐒

**Comment by fedebenelli** [comment]
Hi @SalvadorBrandolin! I appreciate your interest in this library.

We're interested in adding $g^E$ models to our library, but we're still considering the best interface. 

As you probably already know, $g^E$ models are defined both from a $\ln \gamma$ basis and a $G^E$ basis, but both properties are related, there isn't a need to define both as a model definition. It's not available yet but hopefully soon!

This is an open source project so any contributions are welcomed!

**Comment by longemen3000** [comment]
I recommend defining the excess Gibbs energy, and obtaining the activity coefficient via AD. The GE model can be reused, while you need to define the mixing rule used for the cubic in each case (PSRK, VTPR, etc)

**Comment by fedebenelli** [comment]
Thanks for the input @longemen3000! Yes, it makes sense now that I think it in the long term... We'll probably approach it that way

**Comment by fedebenelli** [comment]
To follow history of this issue:

- tapenade API to generate models from a $G^E$ subroutine 
- NRTL model using named API
- UNIFAC model using analytical derivatives, still needs some derivatives and documentation

**Comment by SalvadorBrandolin** [comment]
UNIFAC done :sunglasses:
