### ISSUE TITLE
BUG: Flash doesn't really provide the true light phase

### ISSUE THREAD

**Issue by fedebenelli** [ipqa-research/yaeos#60]
Right now the flash routine assures that the `y` fraction is that of the lighter phase. While it generally works, the approach given now in the flash routine is not the most robust one, since it compares molar volumes and the true density of the phase can differ a lot (or even invert concerning molar volumes) on highly asymmetric mixtures.

For now I would just remove that option and just leave the user to know which phase is lighter. A feasible way to do this would be to convert to mass volumes but I don't like the idea of forcing the user to provide molar weights just for this.

**Comment by fedebenelli** [comment]
For now we provide the solution of the Flash as-is. It's up to the user to know which phase is the light phase.

**Comment by longemen3000** [comment]
What about using the phase identification parameter (Π) ? https://doi.org/10.1016/j.fluid.2010.12.001 (at least in VLE, you cannot differentiate the lighter phase in LLE using Π)

**Comment by fedebenelli** [comment]
Yes! That's a good idea, we had that paper in mind for other part of our algorithms. But now I think it can be a good option in general for our `EquilibriaState` object. Thanks for the input!
