### ISSUE TITLE
UNIFAC

### ISSUE THREAD

**Issue by SalvadorBrandolin** [ipqa-research/yaeos#69]
Ya hay comenzada una implementación de UNIFAC, pero no está dando buenos resultados y aún faltan derivadas

Federico Benelli: https://github.com/ipqa-research/yaeos/blob/dev/src/models/excess_gibbs/group_contribution/unifac.f90#L138 << Esa línea está complicada por algún motivo
[yaeos/src/models/excess_gibbs/group_contribution/unifac.f90 at dev · ipqa-research/yaeos](https://github.com/ipqa-research/yaeos/blob/dev/src/models/excess_gibbs/group_contribution/unifac.f90#L138)

Federico Benelli: O sea, esa ecuación
Federico Benelli: https://thermo.readthedocs.io/thermo.unifac.html#thermo.unifac.UNIFAC.lngammas_r << Referencia

**Comment by longemen3000** [comment]
Otra buena referencia (al menos esa usé yo) https://github.com/thermotools/thermopack/blob/main/docs/memo/UNIFAC/unifac.pdf

**Comment by fedebenelli** [comment]
Gracias! Lo estuve viendo y es muy buena descripción, había tratado de buscar ese pdf dentro de la documentación de `thermopack` pero había un link roto en el momento que busqué
